# Generated by Django 5.2 on 2026-02-10 02:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="https://fontawesome.com/icons",
                        max_length=150,
                        null=True,
                        verbose_name="иконка",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True,
                        help_text="фон",
                        max_length=9,
                        null=True,
                        verbose_name="фон",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="цвет",
                        max_length=9,
                        null=True,
                        verbose_name="цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "default_related_name": "categories",
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="name", max_length=150, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "специалист",
                "verbose_name_plural": "специалисты",
                "default_related_name": "specialists",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, help_text="цена", verbose_name="цена"
                    ),
                ),
                (
                    "is_documents_required",
                    models.BooleanField(
                        default=False,
                        help_text="необходимость документов",
                        verbose_name="необходимость документов",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="категория",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="care.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "specialists",
                    models.ManyToManyField(
                        help_text="специалисты",
                        related_name="services",
                        to="care.specialist",
                        verbose_name="специалисты",
                    ),
                ),
            ],
            options={
                "verbose_name": "сервис",
                "verbose_name_plural": "сервисы",
                "default_related_name": "services",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="date", verbose_name="date")),
                ("time", models.TimeField(help_text="time", verbose_name="time")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="сервис",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="care.service",
                        verbose_name="сервис",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        help_text="специалист",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="care.specialist",
                        verbose_name="специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "прием",
                "verbose_name_plural": "прием",
                "default_related_name": "appointments",
            },
        ),
        migrations.CreateModel(
            name="SpecialistAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="автор оценки",
                        max_length=150,
                        verbose_name="автор оценки",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="date", null=True, verbose_name="date"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="оценка",
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="комментарий",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        help_text="специалист",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="care.specialist",
                        verbose_name="специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "достижение специалиста",
                "verbose_name_plural": "достижения специалистов",
                "default_related_name": "achievements",
            },
        ),
        migrations.CreateModel(
            name="SpecialistReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="автор оценки",
                        max_length=150,
                        verbose_name="автор оценки",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="date", null=True, verbose_name="date"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="оценка",
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="комментарий",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        help_text="специалист",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="care.specialist",
                        verbose_name="специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв на специалиста",
                "verbose_name_plural": "отзывы на специалистов",
                "default_related_name": "reviews",
            },
        ),
    ]
