# Generated by Django 5.2 on 2026-02-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialistachievement",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="specialistachievement",
            name="date",
        ),
        migrations.RemoveField(
            model_name="specialistachievement",
            name="score",
        ),
        migrations.AlterField(
            model_name="specialistachievement",
            name="name",
            field=models.CharField(
                help_text="название", max_length=150, verbose_name="название"
            ),
        ),
    ]
